/* voice.js — optional "Listen" buttons for FIXED site content only.

   Clips are pre-generated by the site author (ElevenLabs, at build time —
   see tools/voice-build.mjs) and shipped as same-origin static files, like
   the font. Pressing play fetches a file from this site and sends nothing
   anywhere; once the service worker has it, it plays offline.

   Deliberately absent: runtime text-to-speech. The only text worth speaking
   at runtime would be the student's own words, and those never leave the
   device — a cloud voice API has no business hearing them.

   The whole feature is dark until media/voice/manifest.json exists: attach()
   appends nothing when a clip isn't listed, so pages render identically
   with or without generated audio. */

import { el } from "./ui.js";

let manifestPromise = null; // resolves to {clipId: "media/voice/….mp3"}
let current = null;         // { audio, btn }

function loadManifest() {
  if (!manifestPromise) {
    manifestPromise = fetch("media/voice/manifest.json")
      .then((res) => (res.ok ? res.json() : null))
      .then((m) => m?.clips || {})
      .catch(() => ({}));
  }
  return manifestPromise;
}

function setPressed(btn, on) {
  btn.classList.toggle("playing", on);
  btn.setAttribute("aria-pressed", String(on));
}

function stop() {
  if (!current) return;
  current.audio.pause();
  setPressed(current.btn, false);
  current = null;
}

// leaving the screen, opening the takeover, or starting another clip all
// silence playback — a voice reading legal guidance under a crisis dialog
// (or over a different answer) would be noise at the worst moment
addEventListener("hashchange", stop);
document.addEventListener("bit:silence", stop);

function icon() {
  // el() builds HTML elements; SVG needs its namespace, so build it directly
  const svg = document.createElementNS("http://www.w3.org/2000/svg", "svg");
  svg.setAttribute("viewBox", "0 0 24 24");
  svg.setAttribute("class", "voice-icon");
  svg.setAttribute("aria-hidden", "true");
  const path = document.createElementNS("http://www.w3.org/2000/svg", "path");
  path.setAttribute("d", "M11 5 6 9H2v6h4l5 4zM15.5 8.5a5 5 0 0 1 0 7M18.4 5.6a9 9 0 0 1 0 12.8");
  path.setAttribute("fill", "none");
  path.setAttribute("stroke", "currentColor");
  path.setAttribute("stroke-width", "2");
  path.setAttribute("stroke-linecap", "round");
  path.setAttribute("stroke-linejoin", "round");
  svg.append(path);
  return svg;
}

export const voice = {
  /** Append a Listen toggle for clip `id` to `container` — if, and only if,
      that clip exists. The name stays constant; aria-pressed carries state
      (same APG toggle pattern as the motion control). */
  attach(container, id, label = "Listen") {
    loadManifest().then((clips) => {
      const src = clips[id];
      if (!src || !container.isConnected) return;
      const btn = el("button", {
        class: "btn btn--ghost voice-btn", type: "button",
        "aria-pressed": "false",
        "aria-label": label + " — pre-recorded, playing sends nothing",
      }, icon(), label);
      btn.addEventListener("click", () => {
        // same button again: pause in place / resume from where it stopped —
        // an interrupted adult must not restart a two-minute briefing at zero
        if (current?.btn === btn) {
          if (current.audio.paused) {
            const cur = current;
            setPressed(btn, true);
            cur.audio.play().catch(() => { if (current === cur) stop(); });
          } else {
            current.audio.pause();
            setPressed(btn, false);
          }
          return;
        }
        stop();
        const audio = new Audio(src);
        current = { audio, btn };
        setPressed(btn, true);
        // guard on identity: a slow clip's late error must not silence
        // whatever replaced it
        const stopIfCurrent = () => { if (current?.audio === audio) stop(); };
        audio.addEventListener("ended", stopIfCurrent);
        audio.addEventListener("error", stopIfCurrent);
        audio.play().catch(stopIfCurrent);
      });
      container.append(btn);
    });
  },
};
